### ISSUE TITLE
Barbs in Southern Hemisphere

### ISSUE THREAD

**Issue by mmuscato** [JoranBeaufort/Leaflet.windbarb#3]
Hello,

Not sure if this is still active but I recently implemented this in a Leaflet map and it works very well. I actually use this to plot forecast data worldwide. The link you have referenced for the wind barbs is correct - for the Northern Hemisphere. For the Southern Hemisphere though, the lines point the other way, like so:
![s_arrows](https://user-images.githubusercontent.com/5577047/33974293-94a77ed8-e07f-11e7-8e09-0e5cf5cae7d5.png)

**Comment by spatialsparks** [comment]
Hi There!
Wow, thanks for the feedback, I havent tested it in the southern hemisphere in all honesty... Could you maybe provide a link to a map showing this? Very good catch, thanks! :)

**Comment by mmuscato** [comment]
Hello,

Sorry for the delay. I appreciate you looking at this! Here is a demo site I just whipped up from our current site we are working on. Let me know if this helps! http://wridolphin.com/demo/index.php

**Comment by spatialsparks** [comment]
Sorry for the late reply :) 
I looked at your example (looks really nice, congrats!) and I cant seem to see what the problem is.
When comparing your map:
![screenshot 2018-01-10 13 09 41](https://user-images.githubusercontent.com/13437059/34772276-c70566b8-f607-11e7-8417-9bf331b9d41b.png)
With another provider:
![screenshot 2018-01-10 13 09 34](https://user-images.githubusercontent.com/13437059/34777339-595d9956-f61a-11e7-90ab-1e38354a08da.png)

Maybe Im not seeing something very obvious, could you highlight the error on a screenshot maybe or something? The planetary wind systems converge at the equator and are opposite on the north and south hemisphere due to the coriolis force. Maybe you have something mixed up? Or maybe, like I said, im not getting something really important ^^

**Comment by mmuscato** [comment]
Thanks! 

Yes, nothing wrong with the actual data. It's a very subtle issue. In the Southern Hemisphere, the flags that determine wind speed are on the other side of the direction post. So let's take that screenshot you sent. If you look at the winds coming from the east, the speed flags should be pointed towards the equator, instead of pointing towards the South Pole.
![34772276-c70566b8-f607-11e7-8417-9bf331b9d41b](https://user-images.githubusercontent.com/5577047/34782446-9c4907ae-f620-11e7-93d1-741a19cdb1a1.png)

Hope this helps!

**Comment by mmuscato** [comment]
Sorry - I attached the wrong image. 
![barbs](https://user-images.githubusercontent.com/5577047/34782528-e4785af2-f620-11e7-8e73-03baa0464008.jpg)
Here is my quick markup on it.

**Comment by spatialsparks** [comment]
Hi!
Thanks for the quick answer, but I still dont quite get what you mean. So you would like to have the windbarb velocity indication mirrored to the other side on the southern hemisphere? Do you have any link which underlines this as being the standard? As far as I can tell, according to a quick search, all velocity indications should be on the same side of the bar shaft, so what you are asking for is more a custom implementation?
cf. https://commons.wikimedia.org/wiki/Wind_speed
Best regards

**Comment by spatialsparks** [comment]
Ps. maybe you can just flip the SVG along the y/2 horizontal line if lat < 0

**Comment by mmuscato** [comment]
Yes, that wikimedia link does not include that information, but it is correct. I have a meteorology textbook that says it along with multiple professors and colleagues. I also just found this post that is asking for the same ability: https://community.esri.com/thread/192254-wind-barb-symbology-southern-hemisphere 

I don't know too much about SVG but if flipping it along the y/2 horizontal line would make the barbs on the other side of bar shaft, then I'm definitely up for that solution!

**Comment by spatialsparks** [comment]
Ah ok, thx for the clarification :) Ill look into it. Maybe in the meantime try flipping the SVG :)

**Comment by mmuscato** [comment]
Thank you!

**Comment by spatialsparks** [comment]
Could you quickly try the new source? Care: now you should pass in the lat as a parameter aswell. not so elegant, but as q quick fix it should work? :)

**Comment by spatialsparks** [comment]
Update: now added the option: rev. If you pass in rev: true as an option, it should mirror the velocity indications. So just do:

```
            if(latitude<0){
              var icon = L.WindBarb.icon({mirrorVel: true, deg: p[3], speed: p[2]});  
            }else{
              var icon = L.WindBarb.icon({lat: p[0], deg: p[3], speed: p[2]});
            }
```

in your script..

**Comment by mmuscato** [comment]
Thanks! Works great! I really appreciate it.

**Comment by spatialsparks** [comment]
No worries :) If you find something else just let me know 👍  Have a good one

**Comment by bibeksh9** [comment]
> Could you quickly try the new source? Care: now you should pass in the lat as a parameter aswell. not so elegant, but as q quick fix it should work? :)

Where is the new source ? I can't see any mirrorVel parameter . 
Thanks

**Comment by bibeksh9** [comment]
Hello @JoranBeaufort  , In some cases that transform is not working means while converting to png  or using in mapbox maki icon.
So , I have tried something that is working fine to flip the barbs without transform .If you want you can include it.
Just replace the   `cy-bh` to `cy+bh`.
I have set it based on your mirrorVel  parameter like this.
`(this.options.mirrorVel ? (cy + bh) : (cy - bh))`
