### ISSUE TITLE
Change units to m/s

### ISSUE THREAD

**Issue by mpca86** [JoranBeaufort/Leaflet.windbarb#5]
It is possible to change or add the option to enter the wind speed in m/s?

**Comment by meersonv** [comment]
I think that a barb signs are developed for knots only, it is non-correct to use them for m/s or other wind speed units.

**Comment by mpca86** [comment]
thx for reply i converted it directly in script..

**Comment by spatialsparks** [comment]
Thanks for replying and sorry for my absence, I have not found time :)
