### ISSUE TITLE
problem with XML and GEOjson

### ISSUE THREAD

**Issue by ghost** [JoranBeaufort/Leaflet.windbarb#7]
Hi Manuel,
I wanna plot windbarb in leaflet with your code. But when I test your code with the example structure that you used it's finely wored. But when I test your code with XML and GEOjson files, I received bad result in wind direction. For example the direction of with with 10 degree with used your code, spot in the direction of 280 degree and so on.
00   00
10   280
20   200
30   120
40    40
50   320
60   180
.
,
,
, 
Can you solve my problem.
Cheers

**Comment by spatialsparks** [comment]
Hi there
If you say that my code is working with the examples but not your data, it is probably something to do with your data or how you read in the data. Check your data at various stages of your import to confirm that nothing gets messed up. Unfortunately, I cant help you with this.
Best
